web:
  image: 'gitlab/gitlab-ce:13.12.5-ce.0'
  restart: always
  hostname: 'gitlab.infra.mbfx.tech-lab.lol'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://178.154.205.157'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
#    - '443:443'
#    - '22:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
  shm_size: '256m'
